/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __LSM_BPF_SKEL_H__
#define __LSM_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct lsm_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *rodata;
	} maps;
	struct {
		struct bpf_program *lsm_bpf;
	} progs;
	struct {
		struct bpf_link *lsm_bpf;
	} links;

#ifdef __cplusplus
	static inline struct lsm_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct lsm_bpf *open_and_load();
	static inline int load(struct lsm_bpf *skel);
	static inline int attach(struct lsm_bpf *skel);
	static inline void detach(struct lsm_bpf *skel);
	static inline void destroy(struct lsm_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
lsm_bpf__destroy(struct lsm_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
lsm_bpf__create_skeleton(struct lsm_bpf *obj);

static inline struct lsm_bpf *
lsm_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct lsm_bpf *obj;
	int err;

	obj = (struct lsm_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = lsm_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	lsm_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct lsm_bpf *
lsm_bpf__open(void)
{
	return lsm_bpf__open_opts(NULL);
}

static inline int
lsm_bpf__load(struct lsm_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct lsm_bpf *
lsm_bpf__open_and_load(void)
{
	struct lsm_bpf *obj;
	int err;

	obj = lsm_bpf__open();
	if (!obj)
		return NULL;
	err = lsm_bpf__load(obj);
	if (err) {
		lsm_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
lsm_bpf__attach(struct lsm_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
lsm_bpf__detach(struct lsm_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *lsm_bpf__elf_bytes(size_t *sz);

static inline int
lsm_bpf__create_skeleton(struct lsm_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "lsm_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "lsm_bpf.rodata";
	s->maps[0].map = &obj->maps.rodata;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "lsm_bpf";
	s->progs[0].prog = &obj->progs.lsm_bpf;
	s->progs[0].link = &obj->links.lsm_bpf;

	s->data = lsm_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *lsm_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xd0\x04\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x09\0\
\x01\0\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x6c\x73\
\x6d\x2f\x62\x70\x66\0\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\x72\x6f\x64\x61\x74\
\x61\0\x6c\x73\x6d\x2e\x62\x70\x66\x2e\x63\0\x4c\x42\x42\x30\x5f\x32\0\x5f\x5f\
\x5f\x5f\x6c\x73\x6d\x5f\x62\x70\x66\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x6c\x73\
\x6d\x5f\x62\x70\x66\0\x4c\x49\x43\x45\x4e\x53\x45\0\x2e\x72\x65\x6c\x6c\x73\
\x6d\x2f\x62\x70\x66\0\x2e\x42\x54\x46\0\x2e\x42\x54\x46\x2e\x65\x78\x74\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x29\0\0\0\x04\0\xf1\xff\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x33\
\0\0\0\0\0\x03\0\x58\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3a\0\0\0\x01\0\x05\0\0\0\0\
\0\0\0\0\0\x18\0\0\0\0\0\0\0\0\0\0\0\x03\0\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x4e\0\0\0\x12\0\x03\0\0\0\0\0\0\0\0\0\x60\0\0\0\0\0\0\0\x56\0\0\0\x11\0\x04\
\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\x79\x10\x18\0\0\0\0\0\xbf\x01\0\0\0\0\0\0\
\x67\x01\0\0\x20\0\0\0\x77\x01\0\0\x20\0\0\0\x55\x01\x06\0\0\0\0\0\x18\x01\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x02\0\0\x18\0\0\0\x85\0\0\0\x06\0\0\0\x18\0\0\0\
\xff\xff\xff\xff\0\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\x47\x50\x4c\0\x4c\x53\x4d\
\x3a\x20\x62\x6c\x6f\x63\x6b\x20\x62\x70\x66\x28\x29\x20\x77\x6f\x72\x6b\x65\
\x64\0\0\0\0\0\x28\0\0\0\0\0\0\0\x01\0\0\0\x05\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\
\0\0\0\xf8\0\0\0\xf8\0\0\0\x34\x01\0\0\0\0\0\0\0\0\0\x02\x02\0\0\0\x01\0\0\0\0\
\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\x01\0\0\x0d\x04\0\0\0\x14\0\0\0\x01\0\0\0\
\x18\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\x1c\0\0\0\x01\0\0\x0c\x03\0\0\0\x24\
\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x06\0\0\0\x08\
\0\0\0\x04\0\0\0\x29\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\x3d\0\0\0\0\0\0\x0e\
\x07\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x0a\x06\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x0a\
\0\0\0\x08\0\0\0\x18\0\0\0\x45\0\0\0\0\0\0\x0e\x0b\0\0\0\0\0\0\0\x1c\x01\0\0\
\x01\0\0\x0f\x04\0\0\0\x09\0\0\0\0\0\0\0\x04\0\0\0\x24\x01\0\0\x01\0\0\x0f\x18\
\0\0\0\x0c\0\0\0\0\0\0\0\x18\0\0\0\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x6c\
\x6f\x6e\x67\x20\x6c\x6f\x6e\x67\0\x63\x74\x78\0\x69\x6e\x74\0\x6c\x73\x6d\x5f\
\x62\x70\x66\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\
\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x4c\x49\x43\x45\x4e\x53\x45\0\x5f\x5f\x5f\
\x5f\x6c\x73\x6d\x5f\x62\x70\x66\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x2f\x68\x6f\
\x6d\x65\x2f\x6c\x6f\x73\x74\x63\x61\x63\x68\x65\x2f\x63\x6f\x64\x65\x2f\x68\
\x65\x6c\x6c\x6f\x5f\x65\x42\x50\x46\x2f\x65\x78\x61\x6d\x70\x6c\x65\x73\x2f\
\x63\x2f\x6c\x73\x6d\x2e\x62\x70\x66\x2e\x63\0\x69\x6e\x74\x20\x42\x50\x46\x5f\
\x50\x52\x4f\x47\x28\x6c\x73\x6d\x5f\x62\x70\x66\x2c\x20\x69\x6e\x74\x20\x63\
\x6d\x64\x2c\x20\x75\x6e\x69\x6f\x6e\x20\x62\x70\x66\x5f\x61\x74\x74\x72\x20\
\x2a\x61\x74\x74\x72\x2c\x20\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\x74\
\x20\x73\x69\x7a\x65\x2c\x20\x69\x6e\x74\x20\x72\x65\x74\x29\0\x20\x20\x20\x20\
\x69\x66\x20\x28\x72\x65\x74\x20\x21\x3d\x20\x30\x29\0\x20\x20\x20\x20\x62\x70\
\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\x22\x4c\x53\x4d\x3a\x20\x62\x6c\x6f\x63\
\x6b\x20\x62\x70\x66\x28\x29\x20\x77\x6f\x72\x6b\x65\x64\x22\x29\x3b\0\x6c\x69\
\x63\x65\x6e\x73\x65\0\x2e\x72\x6f\x64\x61\x74\x61\0\x6c\x73\x6d\x2f\x62\x70\
\x66\0\0\0\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\x4c\0\0\0\
\x60\0\0\0\0\0\0\0\x08\0\0\0\x2c\x01\0\0\x01\0\0\0\0\0\0\0\x05\0\0\0\x10\0\0\0\
\x2c\x01\0\0\x04\0\0\0\0\0\0\0\x59\0\0\0\x8e\0\0\0\x05\x28\0\0\x20\0\0\0\x59\0\
\0\0\xdf\0\0\0\x09\x3c\0\0\x28\0\0\0\x59\0\0\0\xf1\0\0\0\x05\x48\0\0\x58\0\0\0\
\x59\0\0\0\x8e\0\0\0\x05\x28\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x01\0\0\0\x03\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\
\x78\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x09\0\0\0\
\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb8\0\0\0\0\0\0\0\xc0\0\0\0\0\0\0\0\
\x01\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\x11\0\0\0\x01\0\0\0\x06\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x78\x01\0\0\0\0\0\0\x60\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x19\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\xd8\x01\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x21\0\0\0\x01\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\xdc\x01\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x5e\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf8\x01\0\0\
\0\0\0\0\x10\0\0\0\0\0\0\0\x02\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\
\0\0\x6a\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\x02\0\0\0\0\0\0\
\x44\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x6f\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x50\x04\0\0\0\0\0\0\x80\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct lsm_bpf *lsm_bpf::open(const struct bpf_object_open_opts *opts) { return lsm_bpf__open_opts(opts); }
struct lsm_bpf *lsm_bpf::open_and_load() { return lsm_bpf__open_and_load(); }
int lsm_bpf::load(struct lsm_bpf *skel) { return lsm_bpf__load(skel); }
int lsm_bpf::attach(struct lsm_bpf *skel) { return lsm_bpf__attach(skel); }
void lsm_bpf::detach(struct lsm_bpf *skel) { lsm_bpf__detach(skel); }
void lsm_bpf::destroy(struct lsm_bpf *skel) { lsm_bpf__destroy(skel); }
const void *lsm_bpf::elf_bytes(size_t *sz) { return lsm_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
lsm_bpf__assert(struct lsm_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __LSM_BPF_SKEL_H__ */
